language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - cd test
  - pytest --cov=dialer --cov-fail-under=25 test

# integration with coveralls seems to be tricky and left out of scope of this exercise
# minor change to trigger a build